[package]
name = "wslwrap"
version = "0.1.3"
authors = ["TheGoddessInari <thegoddessinari@gmail.com>"]
edition = "2018"

[dependencies]
lazy_static = "1.0"
regex = "1"
env_logger = "0.6"

[dependencies.log]
version = "0.4"
features = ["max_level_debug", "release_max_level_warn"]