[package]
name = "wslwrap"
version = "0.2.0"
authors = ["TheGoddessInari <thegoddessinari@gmail.com>"]
edition = "2018"

[dependencies]

[profile.release]
lto = true
codegen-units = 1
opt-level = "z"
